name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        aliyun_username: ${{secrets.DOCKER_USERNAME}} 
        aliyun_password: ${{secrets.DOCKER_PASSWORD}} 
        image_name: v2-ui
        image_version: $(echo "${{ github.sha }}" | sed -e 's,.*/\(.*\),\1,')
      run: |
        docker login --username=${aliyun_username} --password=${aliyun_password} registry.cn-qingdao.aliyuncs.com
        docker build . --file Dockerfile --tag ${image_name}:${image_version}
        docker tag ${image_name}:${image_version} registry.cn-qingdao.aliyuncs.com/thesadboy/${image_name}:${image_version}
        docker push registry.cn-qingdao.aliyuncs.com/thesadboy/${image_name}:${image_version}
