name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        aliyun_username: ${{secrets.DOCKER_USERNAME}} 
        aliyun_password: ${{secrets.DOCKER_PASSWORD}} 
      run: |
        IMAGE_NAME=v2-ui
        IMAGE_VERSION=$(echo "${{ github.sha }}" | cut -c 1-8)
        docker login --username=${aliyun_username} --password=${aliyun_password} registry.cn-qingdao.aliyuncs.com
        docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_VERSION
        docker tag $IMAGE_NAME:$IMAGE_VERSION registry.cn-qingdao.aliyuncs.com/thesadboy/$IMAGE_NAME:$IMAGE_VERSION
        docker push registry.cn-qingdao.aliyuncs.com/thesadboy/$IMAGE_NAME:$IMAGE_VERSION
